import { NextRequest, NextResponse } from 'next/server';
import { READING_QUESTIONS, LISTENING_QUESTIONS } from '@/lib/questions';
import {
  generateReadingQuestions,
  generateListeningQuestions,
  generateVocabQuestions,
  generateSpeakingTopics,
  generateWritingPrompts,
} from '@/lib/agnes';

/**
 * Agnes AI 驱动的智能出题接口
 * 调用 AI 动态生成各类题目，AI 不可用时回退到静态题库
 */
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const type = searchParams.get('type') ?? 'reading';
  const count = parseInt(searchParams.get('count') ?? '5', 10);
  const difficulty = (searchParams.get('difficulty') ?? 'B1') as 'A2' | 'B1' | 'B2' | 'C1';

  try {
    let questions: unknown[] = [];
    const model = 'agnes-v2-chat';

    switch (type) {
      case 'reading':
        questions = await generateReadingQuestions(count);
        break;
      case 'listening':
        questions = await generateListeningQuestions(count);
        break;
      case 'vocabulary':
        questions = await generateVocabQuestions(count, difficulty);
        break;
      case 'speaking':
        questions = await generateSpeakingTopics(count);
        break;
      case 'writing':
        questions = await generateWritingPrompts(count);
        break;
      default:
        return NextResponse.json({
          success: true,
          questions: [],
          meta: { model: 'agnes-v2-chat', note: `Unknown type: "${type}". Supported: reading, listening, vocabulary, speaking, writing`, generated_at: new Date().toISOString() },
        });
    }

    return NextResponse.json({
      success: true,
      questions,
      meta: {
        model,
        note: 'Generated by Agnes AI',
        generated_at: new Date().toISOString(),
      },
    });
  } catch (error) {
    // AI 不可用 → 回退到静态题库
    console.warn('Agnes AI unavailable, falling back to static question bank:', error);

    let questions: unknown[] = [];
    const pool = type === 'listening' ? LISTENING_QUESTIONS
      : type === 'reading' ? READING_QUESTIONS
      : [];

    if (pool.length > 0) {
      questions = pool.slice(0, Math.min(count, pool.length));
    }

    return NextResponse.json({
      success: true,
      questions,
      meta: {
        model: 'mock-v1-fallback',
        note: 'Fallback to static question bank. Agnes AI was unavailable.',
        generated_at: new Date().toISOString(),
      },
    });
  }
}

/** POST 接口接受 prompt 生成自定义题目 */
export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => ({}));
  const { prompt, type: qType = 'reading' } = body;

  try {
    let questions: unknown[] = [];

    switch (qType) {
      case 'reading':
        questions = await generateReadingQuestions(1);
        break;
      case 'listening':
        questions = await generateListeningQuestions(1);
        break;
      case 'vocabulary':
        questions = await generateVocabQuestions(1, body.difficulty ?? 'B1');
        break;
      case 'speaking':
        questions = await generateSpeakingTopics(1);
        break;
      case 'writing':
        questions = await generateWritingPrompts(1);
        break;
    }

    return NextResponse.json({
      success: true,
      question: questions[0] ?? null,
      meta: {
        model: 'agnes-v2-chat',
        prompt_received: prompt ?? null,
        generated_at: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.warn('Agnes AI POST unavailable, returning mock:', error);
    return NextResponse.json({
      success: true,
      message: 'Agnes AI unavailable. Returning mock data.',
      question: READING_QUESTIONS[0],
      meta: {
        model: 'mock-v1-fallback',
        prompt_received: prompt ?? null,
      },
    });
  }
}
